# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_add_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.10

from PyQt5 import QtCore, QtGui, QtWidgets
import gui_utils

class Ui_addProjectWindow(object):
    def setupUi(self, addProjectWindow):
        addProjectWindow.setObjectName("addProjectWindow")
        addProjectWindow.resize(640, 280)
        addProjectWindow.setMinimumSize(QtCore.QSize(600, 200))
        addProjectWindow.setMaximumSize(QtCore.QSize(1000, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/rikor_ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addProjectWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(addProjectWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nameLine = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLine.setGeometry(QtCore.QRect(10, 30, 180, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.nameLine.setFont(font)
        self.nameLine.setObjectName("nameLine")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(10, 5, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.nameLabel.setFont(font)
        self.nameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.componentsLabel = QtWidgets.QLabel(self.centralwidget)
        self.componentsLabel.setGeometry(QtCore.QRect(390, 5, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.componentsLabel.setFont(font)
        self.componentsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.componentsLabel.setObjectName("componentsLabel")
        self.bgImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.bgImageLabel.setGeometry(QtCore.QRect(0, 0, 640, 280))
        self.bgImageLabel.setStyleSheet("background-image: url(:/bg/main_bg_640x280.jpg);")
        self.bgImageLabel.setText("")
        self.bgImageLabel.setObjectName("bgImageLabel")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(490, 230, 141, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.addButton.setFont(font)
        self.addButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addButton.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.addButton.setObjectName("addButton")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(340, 230, 141, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.cancelButton.setFont(font)
        self.cancelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelButton.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.cancelButton.setObjectName("cancelButton")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(10, 170, 280, 100))
        self.logoLabel.setStyleSheet("background-image: url(:/logoImage/rikor_logo_280x100.png);")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(390, 30, 241, 191))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.toolBox.setFont(font)
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolBox.setObjectName("toolBox")
        self.processor = QtWidgets.QWidget()
        self.processor.setGeometry(QtCore.QRect(0, 0, 241, 39))
        self.processor.setObjectName("processor")
        self.processorBox = QtWidgets.QComboBox(self.processor)
        self.processorBox.setGeometry(QtCore.QRect(0, 0, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.processorBox.setFont(font)
        self.processorBox.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.processorBox.setEditable(False)
        self.processorBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.processorBox.setObjectName("processorBox")
        self.toolBox.addItem(self.processor, "")
        self.videocard = QtWidgets.QWidget()
        self.videocard.setGeometry(QtCore.QRect(0, 0, 241, 39))
        self.videocard.setObjectName("videocard")
        self.videocardBox = QtWidgets.QComboBox(self.videocard)
        self.videocardBox.setGeometry(QtCore.QRect(0, 0, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.videocardBox.setFont(font)
        self.videocardBox.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.videocardBox.setEditable(False)
        self.videocardBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.videocardBox.setObjectName("videocardBox")
        self.toolBox.addItem(self.videocard, "")
        self.ram = QtWidgets.QWidget()
        self.ram.setGeometry(QtCore.QRect(0, 0, 241, 39))
        self.ram.setObjectName("ram")
        self.ramBox = QtWidgets.QComboBox(self.ram)
        self.ramBox.setGeometry(QtCore.QRect(0, 0, 180, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.ramBox.setFont(font)
        self.ramBox.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.ramBox.setEditable(False)
        self.ramBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.ramBox.setObjectName("ramBox")
        self.spinCount = QtWidgets.QSpinBox(self.ram)
        self.spinCount.setGeometry(QtCore.QRect(190, 0, 51, 31))
        self.spinCount.setObjectName("spinCount")
        self.toolBox.addItem(self.ram, "")
        self.storage_device = QtWidgets.QWidget()
        self.storage_device.setGeometry(QtCore.QRect(0, 0, 241, 39))
        self.storage_device.setObjectName("storage_device")
        self.storageBox = QtWidgets.QComboBox(self.storage_device)
        self.storageBox.setGeometry(QtCore.QRect(0, 0, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.storageBox.setFont(font)
        self.storageBox.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.storageBox.setEditable(False)
        self.storageBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.storageBox.setObjectName("storageBox")
        self.toolBox.addItem(self.storage_device, "")
        self.priceLine = QtWidgets.QLineEdit(self.centralwidget)
        self.priceLine.setGeometry(QtCore.QRect(200, 30, 180, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.priceLine.setFont(font)
        self.priceLine.setObjectName("priceLine")
        self.priceLabel = QtWidgets.QLabel(self.centralwidget)
        self.priceLabel.setGeometry(QtCore.QRect(200, 5, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.priceLabel.setFont(font)
        self.priceLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.priceLabel.setObjectName("priceLabel")
        self.bgImageLabel.raise_()
        self.nameLine.raise_()
        self.nameLabel.raise_()
        self.componentsLabel.raise_()
        self.addButton.raise_()
        self.cancelButton.raise_()
        self.logoLabel.raise_()
        self.toolBox.raise_()
        self.priceLine.raise_()
        self.priceLabel.raise_()
        addProjectWindow.setCentralWidget(self.centralwidget)

        self.spinCount.setMaximum(8)
        self.spinCount.setMinimum(1)
        self.addButton.clicked.connect(self.addProject)
        self.fillComponentBoxes()
        self.cancelButton.clicked.connect(addProjectWindow.close)

        self.retranslateUi(addProjectWindow)
        self.toolBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(addProjectWindow)

    def retranslateUi(self, addProjectWindow):
        _translate = QtCore.QCoreApplication.translate
        addProjectWindow.setWindowTitle(_translate("addProjectWindow", "Добавить проект"))
        self.nameLabel.setText(_translate("addProjectWindow", "имя"))
        self.componentsLabel.setText(_translate("addProjectWindow", "комплектующие"))
        self.addButton.setText(_translate("addProjectWindow", "Добавить"))
        self.cancelButton.setText(_translate("addProjectWindow", "Отмена"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.processor), _translate("addProjectWindow", "процессор"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.videocard), _translate("addProjectWindow", "видеокарта"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ram), _translate("addProjectWindow", "оперативная память"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.storage_device), _translate("addProjectWindow", "хранилище"))
        self.priceLabel.setText(_translate("addProjectWindow", "стоимость"))

    def clearFields(self):
        self.nameLine.setText("")
        self.priceLine.setText("")
        self.spinCount.setValue(1)

    addProject = gui_utils.addProject
    message = gui_utils.message
    fillComponentBoxes = gui_utils.fillComponentBoxes

    def __init__(self, data):
        self.data = data

import main_bg_600x200_rc
import main_bg_640x280_rc
import rikor_logo_280x100_rc