#include "../inc/sort_data.h"

COMPONENT GET_COMPONENT(
		unsigned int 	ID,
		char*			TYPE,
		char*			NAME,
		unsigned int 	COUNT)
{
	COMPONENT LOCAL_COMPONENT;

	LOCAL_COMPONENT.TYPE = (char*)malloc(30*sizeof(char));
	LOCAL_COMPONENT.NAME = (char*)malloc(30*sizeof(char));

	LOCAL_COMPONENT.ID = ID;
	strcpy(LOCAL_COMPONENT.TYPE, TYPE);
	strcpy(LOCAL_COMPONENT.NAME, NAME);
	LOCAL_COMPONENT.COUNT = COUNT;

	return LOCAL_COMPONENT;
}

PROJECT GET_PROJECT(
		unsigned int 	ID,
		char*			NAME,
		COMPONENT 		PROCESSOR,
		COMPONENT 		VIDEOCARD,
		COMPONENT 		RAM,
		unsigned int 	RAM_COUNT,
		COMPONENT 		STORAGE_DEVICE,
		float 			PRICE)
{
	PROJECT LOCAL_PROJECT;

	LOCAL_PROJECT.NAME = (char*)malloc(30*sizeof(char));

	LOCAL_PROJECT.ID = ID;
	strcpy(LOCAL_PROJECT.NAME, NAME);
	LOCAL_PROJECT.PROCESSOR = PROCESSOR;
	LOCAL_PROJECT.VIDEOCARD = VIDEOCARD;
	LOCAL_PROJECT.RAM = RAM;
	LOCAL_PROJECT.RAM_COUNT = RAM_COUNT;
	LOCAL_PROJECT.STORAGE_DEVICE = STORAGE_DEVICE;
	LOCAL_PROJECT.PRICE = PRICE;

	return LOCAL_PROJECT;
}

PRODUCT GET_PRODUCT(
		unsigned int 	ID,
		PROJECT 		PROJECT,
		unsigned int 	COUNT)
{
	PRODUCT LOCAL_STORAGE;

	LOCAL_STORAGE.ID = ID;
	LOCAL_STORAGE.PROJECT = PROJECT;
	LOCAL_STORAGE.COUNT = COUNT;

	return LOCAL_STORAGE;
}

DATA GET_DATA(
		COMPONENT*		COMPONENTS,
		PROJECT* 		PROJECTS,
		PRODUCT* 		PRODUCTS)
{
	DATA LOCAL_DATA;

	for(unsigned int i = 0; i < 256; i++)
		{LOCAL_DATA.COMPONENTS[i] = COMPONENTS[i];}

	for(unsigned int i = 0; i < 256; i++)
		{LOCAL_DATA.PROJECTS[i] = PROJECTS[i];}

	for(unsigned int i = 0; i < 256; i++)
		{LOCAL_DATA.PRODUCTS[i] = PRODUCTS[i];}

	return LOCAL_DATA;
}
